# Code generated by protoc-gen-activemodel. DO NOT EDIT.
# frozen_string_literal: true
# source: common.proto

module Common; end

class Common::Context
  include ActiveModel::Model
  
  attribute :context_id, Integer, description: ""
end

