# frozen_string_literal: true
# Code generated by protoc-gen-activemodel. DO NOT EDIT.
# source: common.proto

module Common; end

class Common::Context
  include ActiveModel::Model
  
  attribute :context_id, :integer, description: ""
end
