# frozen_string_literal: true
# Code generated by protoc-gen-activemodel. DO NOT EDIT.
# source: example.proto

module Example; end

class Example::Request
  include ActiveModel::Model
  
  attribute :name, :string, description: ""
  attribute :context, Common::Context, description: ""
end

class Example::Response
  include ActiveModel::Model
  
  attribute :greeting, :string, description: ""
end
